version: "3.9"

services:

  clickhouse:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"

  vertica:
    image: jbfavre/vertica:9.2.0-7_debian-8
    ports:
      - "5433:5433"
