version: "3.9"

services:

  test_stand:
    container_name: "test_stand"
    build: ./
    environment:
      - INITIAL_ROWS_COUNT=10_000_000
      - STRESS_TESTS_WPS=10_000
      - CLICKHOUSE_HOST=clickhouse
      - VERTICA_HOST=vertica

  clickhouse:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    expose:
      - "9000"

  vertica:
    image: jbfavre/vertica:9.2.0-7_debian-8
    expose:
      - "5433"
