version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s %(message)s"
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: "%(levelprefix)s %(client_addr)s - %(request_line)s - %(status_code)s"

handlers:
  console:
    formatter: verbose
    class: logging.StreamHandler
    level: DEBUG
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  '':
    handlers: [console]
    level: INFO
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    propagate: false
    level: INFO
  services.producer:
    handlers: [console]
    level: DEBUG

root:
  formatter: verbose
  handlers: [console]
  level: INFO
