@startuml to_be
!theme materia
skinparam componentStyle uml2

title TO_BE

agent Client
agent SuperUser
card NGINX
card Jaeger
database ElasticsearchMovies


node AdminService {
    frame DjangoAdmin {
        component DjangoAPI
        component DjangoAdminPanel
    }

    database PostgresMovies

    frame PostgresToElasticETL {
        database CurrentState
        file Extract
        file Transform
        file Load

        CurrentState -> Extract: проверка текущего состояния
        Load -> CurrentState: обновление состояния
        
        Extract -> Transform
        Transform -> Load
    }
}


node AsyncService {
    database AsyncRedisCache
    frame AsyncAPI {
        component Async_Services
        file AsyncTracer
    }

    Async_Services <-> AsyncRedisCache: кэширование
    AsyncTracer -> Jaeger: отправление трейсов Jaeger
}


node AuthService {
    database Users
    database AuthRedisCache
    frame AuthAPI {
        component Auth_Services
        file AuthTracer
        cloud OAuth2 {
            component Yandex
            component VK
        }
    }
    
    Auth_Services <--> Users: работа с данными пользователей
    Auth_Services <--> AuthTracer
    Auth_Services <--> OAuth2: авторизация через соц.сети
    Auth_Services <--> AuthRedisCache: хранение jwt токенов
    
    AuthTracer -> Jaeger: отправление трейсов Jaeger
}

node UGCService {
    card Zookeeper

    frame OLTP {
        file UGCAPI
        database Kafka
    }
    
    UGCAPI --> Kafka

    frame UGC_ETL{
        file UGC_Extract
        file UGC_Transform
        file UGC_Load
    }

    frame OLAP {
        database ClickHouse
    }

    Zookeeper <-up-> Kafka
    Zookeeper <-up-> ClickHouse

    Kafka -up-> UGC_Extract: данные о событии
    UGC_Extract -left-> UGC_Transform
    UGC_Transform -left-> UGC_Load
    UGC_Load --> ClickHouse: данные о событии

}

NGINX <-up-> Client: запросы [пользователь]
NGINX <-up-> SuperUser: запросы [модераторы, админ]
NGINX <-> DjangoAdminPanel: доступ к админ панели
NGINX <.[#Purple].> DjangoAPI: legacy movies API
NGINX <-> AsyncAPI: API полнотекстового поиска
NGINX <-> AuthAPI: API авторизации
NGINX <..> Jaeger: доступ к Jaeger
NGINX <-down-> UGCAPI: API контента, сгенерированного поиска

PostgresMovies -> Extract: выгрузка данных из Postgres
PostgresMovies <.[#Purple].> DjangoAPI: legacy movies api
PostgresMovies <--> DjangoAdminPanel

Load -> ElasticsearchMovies: загрузка данных в ElasticSearch
ElasticsearchMovies <--> Async_Services: взятие данных из elastic
ElasticsearchMovies <.[#Purple].> DjangoAPI: legacy movies api

SuperUser <.> Jaeger: запросы [аналитики, админ]

@enduml