summary: Удаление роли
description: API для удаления роли
tags:
  - v1/roles
security:
  - BearerAuth: []
parameters:
  - in: path
    name: role_id
    schema:
      type: string
      format: uuid
    required: true
    description: UUID роли

responses:
  200:
    description: Success
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Role deleted

  401:
    description: Unauthorized
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Missing Authorization Header

  403:
    description: Forbidden
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Access denied

  422:
    description: Unprocessable Entity
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Not enough segments
