summary: Добавление роли
description: API для добавления роли
tags:
  - v1/roles
security:
  - BearerAuth: []
requestBody:
  description: json с именем роли
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          name:
            type: string
      examples:
        example:
          summary: example
          value:
            name: rolename

responses:
  200:
    description: Success
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
        examples:
          example:
            summary: example
            value:
              id: f2b6ce8a-4770-4550-b570-f6b040fdbb06
              name: rolename

  400:
    description: Bad request
    content:
      application/json:
        schema:
          type: object
          properties:
            result:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Invalid body request

  401:
    description: Unauthorized
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Missing Authorization Header

  403:
    description: Forbidden
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Access denied

  422:
    description: Unprocessable Entity
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Not enough segments
