summary: Получения информации о роле
description: API для получения информации о роле
tags:
  - v1/roles
security:
  - BearerAuth: []
parameters:
  - in: path
    name: role_id
    schema:
      type: string
      format: uuid
    required: true
    description: UUID роли
    
responses:
  
  200:
    description: Success
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
        examples:
          example:
            summary: example
            value:
              id: f2b6ce8a-4770-4550-b570-f6b040fdbb06
              name: role_name
  
  401:
    description: Unauthorized
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Missing Authorization Header

  403:
    description: Forbidden
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Access denied
  422:
    description: Unprocessable Entity
    content:
      application/json:
        schema:
          type: object
          properties:
            msg:
              type: string
        examples:
          example:
            summary: example
            value:
              msg: Not enough segments
