"""empty message

Revision ID: ebb1a608962d
Revises: 3187042f56e1
Create Date: 2023-03-01 12:26:56.894078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'ebb1a608962d'
down_revision = '3187042f56e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_id', sa.Text(), nullable=False),
    sa.Column('social_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id', 'social_name'),
    sa.UniqueConstraint('social_id', 'social_name', name='social_pk'),
    sa.UniqueConstraint('id', 'social_name'),
    postgresql_partition_by='LIST (social_name)',
    )

    connection = op.get_bind()
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS "social_account_vk" PARTITION OF "social_account" FOR VALUES IN ('vk');
        """))
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS "social_account_google" PARTITION OF "social_account" FOR VALUES IN ('google');
        """))
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS "social_account_yandex" PARTITION OF "social_account" FOR VALUES IN ('yandex');
        """))
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS "social_account_mailru" PARTITION OF "social_account" FOR VALUES IN ('mailru');
        """))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('social_account')
    # ### end Alembic commands ###
