name: CI

on:
    push:
        branches: [ main, CICD ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint with mypy
              run: pip install mypy &&
                mypy --strict .

            - name: Lint with flake8
              run: pip install flake8 flake8-html &&
                flake8 --format=html --htmldir=flake-report

    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Async service tests
              run: cp fastapi-solution/tests/functional/.env.sample fastapi-solution/tests/functional/.env &&
                make async_tests

    send_notification:
        needs: [ lint, tests ]
        runs-on: ubuntu-latest
        steps:
            - name: Send Telegram notification
              if: always()
              env:
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
                -d chat_id=${TELEGRAM_CHAT_ID} \
                -d text="CI succeeded!"
