name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint with mypy
              run: pip install mypy &&
                mypy .

            - name: Lint with flake8
              run: pip install flake8 flake8-html &&
                flake8 --format=html --htmldir=flake-report

    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch
              uses: actions/checkout@v3
            
            - name: Running tests
              run: echo

    send_notification:
        needs: [ lint, tests ]
        runs-on: ubuntu-latest
        steps:
            - name: Send Telegram notification
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: |
                  ${{ github.actor }} created commit:
                  Commit message: ${{ github.event.commits[0].message }}
                  
                  Repository: ${{ github.repository }}
                  
                  See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
